toml-version = "v1.0.0"

[format]
[format.rules]
array-bracket-space-width = 1
array-comma-space-width = 1
date-time-delimiter = "T"
indent-style = "space"
indent-sub-tables = true
indent-table-key-value-pairs = false
indent-width = 4
inline-table-brace-space-width = 1
inline-table-comma-space-width = 1
key-value-equals-sign-alignment = false
key-value-equals-sign-space-width = 1
line-ending = "lf"
line-width = 120
string-quote-style = "preserve"
trailing-comment-alignment = true
trailing-comment-space-width = 2

[lint]
[lint.rules]
dotted-keys-out-of-order = "warn"
key-empty = "warn"
tables-out-of-order = "warn"

[schema]
enabled = true
strict = true

# Sub Schema
[[schemas]]
path = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
include = ["*.omp.toml"]

[[overrides]]

[overrides.files]
include = ["specific/**/*.toml"]
# exclude = ["specific/**/ignored.toml"]


